//
//  FeatureToggle.swift
//  Scyther
//
//  Created by Brandon Stillitano on 3/12/20.
//

import Foundation

/// A feature flag that can be toggled remotely or locally.
///
/// `FeatureToggle` represents a single feature flag with support for:
/// - Remote configuration from a server
/// - Local overrides stored in UserDefaults
///
/// ## Usage
/// ```swift
/// let toggle = FeatureToggle(
///     name: "New Dashboard",
///     remoteValue: false
/// )
///
/// if toggle.value {
///     // Show new dashboard
/// }
///
/// // Override locally for testing
/// toggle.localValue = true
/// ```
public struct FeatureToggle {
    /// Creates a new feature toggle.
    ///
    /// - Parameters:
    ///   - name: The unique name identifying this feature toggle.
    ///   - remoteValue: The value received from the remote configuration server.
    public init(name: String, remoteValue: Bool) {
        self.name = name
        self.remoteValue = remoteValue
    }

    /// The unique name identifying this feature toggle.
    ///
    /// This should be unique across all toggles, as registering a duplicate name will replace
    /// the previous entry.
    public internal(set) var name: String

    /// The computed value of this feature toggle.
    ///
    /// Returns the local override value.
    ///
    /// - Returns: `true` if the feature is enabled, `false` otherwise.
    public var value: Bool {
        return localValue
    }

    /// The UserDefaults key for storing the local override value.
    ///
    /// Generated by converting the toggle name to lowercase, replacing spaces with underscores,
    /// and prefixing with `Scyther_toggler_local_value_`.
    ///
    /// Example: "Secret Feature" becomes "Scyther_toggler_local_value_secret_feature"
    ///
    /// - Complexity: O(*n*) where *n* is the length of the name.
    private var defaultsKey: String {
        return "Scyther_toggler_local_value_\(name.lowercased().replacingOccurences(of: [" "], with: "_"))"
    }

    /// The value received from the remote configuration server.
    ///
    /// This represents the server-side state of the feature toggle and should be set
    /// when initializing from remote configuration.
    ///
    /// - Complexity: O(1)
    public internal(set) var remoteValue: Bool = false

    /// The local override value for this feature toggle.
    ///
    /// When set, the value is persisted to UserDefaults. This allows developers to override
    /// feature flags during development and testing without modifying server configuration.
    ///
    /// - Complexity: O(1)
    public var localValue: Bool {
        get {
            return UserDefaults.standard.bool(forKey: defaultsKey)
        }
        set {
            UserDefaults.standard.setValue(newValue, forKey: defaultsKey)
        }
    }
}
