//
//  FeatureToggle.swift
//  Scyther
//
//  Created by Brandon Stillitano on 3/12/20.
//

import Foundation

/// A feature flag that can be toggled remotely or locally with optional A/B testing support.
///
/// `FeatureToggle` represents a single feature flag with support for:
/// - Remote configuration from a server
/// - Local overrides stored in UserDefaults
/// - A/B testing with conditional expressions
///
/// ## Usage
/// ```swift
/// let toggle = FeatureToggle(
///     name: "New Dashboard",
///     remoteValue: false,
///     abValue: "percentage < 50"  // Optional A/B test condition
/// )
///
/// if toggle.value {
///     // Show new dashboard to qualified users
/// }
///
/// // Override locally for testing
/// toggle.localValue = true
/// ```
public struct FeatureToggle {
    /// Creates a new feature toggle.
    ///
    /// - Parameters:
    ///   - name: The unique name identifying this feature toggle.
    ///   - remoteValue: The value received from the remote configuration server.
    ///   - abValue: Optional conditional expression for A/B testing. When provided, this takes
    ///              precedence over `localValue`. The expression is evaluated using the
    ///              `ShuntingYardResolver` to determine the toggle state.
    /// - Complexity: O(1)
    public init(name: String, remoteValue: Bool, abValue: String? = nil) {
        self.name = name
        self.remoteValue = remoteValue
        self.abValue = abValue
    }

    /// Conditional expression string for A/B testing.
    ///
    /// When set, this expression is evaluated to determine the toggle state, taking precedence
    /// over local values. The expression can reference device conditions like app version,
    /// device type, and user cohort percentage.
    private var abValue: String?

    /// The unique name identifying this feature toggle.
    ///
    /// This should be unique across all toggles, as registering a duplicate name will replace
    /// the previous entry.
    public internal(set) var name: String

    /// The computed value of this feature toggle.
    ///
    /// The value is determined in the following priority order:
    /// 1. If `abValue` is set, evaluate the A/B test expression
    /// 2. Otherwise, return the `localValue`
    ///
    /// - Returns: `true` if the feature is enabled, `false` otherwise.
    /// - Complexity: O(1) for local values, O(*n*) for A/B expressions where *n* is the
    ///               number of conditions in the expression.
    public var value: Bool {
        // Check A/B test expression first as it takes priority
        guard abValue == nil else {
            return ShuntingYardResolver.instance.evaluate(expression: abValue)
        }
        return localValue
    }

    /// The UserDefaults key for storing the local override value.
    ///
    /// Generated by converting the toggle name to lowercase, replacing spaces with underscores,
    /// and prefixing with `Scyther_toggler_local_value_`.
    ///
    /// Example: "Secret Feature" becomes "Scyther_toggler_local_value_secret_feature"
    ///
    /// - Complexity: O(*n*) where *n* is the length of the name.
    private var defaultsKey: String {
        return "Scyther_toggler_local_value_\(name.lowercased().replacingOccurences(of: [" "], with: "_"))"
    }

    /// The value received from the remote configuration server.
    ///
    /// This represents the server-side state of the feature toggle and should be set
    /// when initializing from remote configuration.
    ///
    /// - Complexity: O(1)
    public internal(set) var remoteValue: Bool = false

    /// The local override value for this feature toggle.
    ///
    /// When set, the value is persisted to UserDefaults. This allows developers to override
    /// feature flags during development and testing without modifying server configuration.
    ///
    /// - Complexity: O(1)
    public var localValue: Bool {
        get {
            return UserDefaults.standard.bool(forKey: defaultsKey)
        }
        set {
            UserDefaults.standard.setValue(newValue, forKey: defaultsKey)
        }
    }
}
